include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - [build/**]
    - lib/src/locations.g.dart

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps